#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: 356da62
#
Name     : R-sfd
Version  : 0.1.0
Release  : 2
URL      : https://cran.r-project.org/src/contrib/sfd_0.1.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/sfd_0.1.0.tar.gz
Summary  : Space-Filling Design Library
Group    : Development/Tools
License  : MIT
Requires: R-cli
Requires: R-rlang
Requires: R-tibble
BuildRequires : R-cli
BuildRequires : R-rlang
BuildRequires : R-tibble
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
A collection of pre-optimized space-filling designs, for up to ten 
    parameters, is contained here. Functions are provided to access designs

%prep
%setup -q -n sfd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722354932

%install
export SOURCE_DATE_EPOCH=1722354932
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/sfd/DESCRIPTION
/usr/lib64/R/library/sfd/INDEX
/usr/lib64/R/library/sfd/LICENSE
/usr/lib64/R/library/sfd/Meta/Rd.rds
/usr/lib64/R/library/sfd/Meta/data.rds
/usr/lib64/R/library/sfd/Meta/features.rds
/usr/lib64/R/library/sfd/Meta/hsearch.rds
/usr/lib64/R/library/sfd/Meta/links.rds
/usr/lib64/R/library/sfd/Meta/nsInfo.rds
/usr/lib64/R/library/sfd/Meta/package.rds
/usr/lib64/R/library/sfd/NAMESPACE
/usr/lib64/R/library/sfd/NEWS.md
/usr/lib64/R/library/sfd/R/sfd
/usr/lib64/R/library/sfd/R/sfd.rdb
/usr/lib64/R/library/sfd/R/sfd.rdx
/usr/lib64/R/library/sfd/WORDLIST
/usr/lib64/R/library/sfd/data/Rdata.rdb
/usr/lib64/R/library/sfd/data/Rdata.rds
/usr/lib64/R/library/sfd/data/Rdata.rdx
/usr/lib64/R/library/sfd/help/AnIndex
/usr/lib64/R/library/sfd/help/aliases.rds
/usr/lib64/R/library/sfd/help/figures/README-designs-1.png
/usr/lib64/R/library/sfd/help/paths.rds
/usr/lib64/R/library/sfd/help/sfd.rdb
/usr/lib64/R/library/sfd/help/sfd.rdx
/usr/lib64/R/library/sfd/html/00Index.html
/usr/lib64/R/library/sfd/html/R.css
/usr/lib64/R/library/sfd/tests/spelling.R
/usr/lib64/R/library/sfd/tests/testthat.R
/usr/lib64/R/library/sfd/tests/testthat/_snaps/making-designs.md
/usr/lib64/R/library/sfd/tests/testthat/_snaps/setting-values.md
/usr/lib64/R/library/sfd/tests/testthat/test-making-designs.R
/usr/lib64/R/library/sfd/tests/testthat/test-setting-values.R
